services:
  db:
    image: postgres:17
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    networks:
      - app_network

  api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app_network

  # Next.js service
  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - api
      - frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
