name: Build Docker Compose

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # Step 5: Build and start the Docker Compose services
      - name: Build and Start Docker Compose
        run: |
          docker-compose up --build -d  # Build and start containers in detached mode
