name: Build Docker Compose

on:
  # Run this workflow on pushes and pull requests to any branch
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
