name: Build Docker Compose

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose
        uses: docker/build-push-action@v6
        with:
          push: false
