name: "Test backend with Django test"

on: [pull_request, push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify Python version, like '3.9' or '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./backend
      - name: Run Tests
        run: |
          python manage.py test
        working-directory: ./backend
