name: "Test backend with Django test"

on: [pull_request, push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify Python version, like '3.9' or '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./backend
      - name: Run Tests
        env: # Set environment variables here
          DJANGO_SUPERUSER_PASSWORD: "test"
          DJANGO_SUPERUSER_USERNAME: "test"
          DJANGO_SUPERUSER_EMAIL: ""
          DB_NAME: "test"
          DB_USER: "postgres"
          DB_PASSWORD: "test"
          DB_PORT: "5432"
          DB_HOST: "db"
          WEB_PORT: "8000"
          CORS_ALLOW_ALL_ORIGINS: "True"
        run: |
          python manage.py test
        working-directory: ./backend
